set_project("TRNG successor")
set_policy("package.install_locally", true)
set_policy("build.warning", true)
add_rules("mode.debug","mode.release","mode.releasedbg","mode.minsizerel","plugin.compile_commands.autoupdate", {outputdir = "$(buildir)"})
includes("TOMB4/xmake.lua")