add_requires("miniaudio","zlib", "xaudio2redist")
target("trng2")
	add_packages("zlib")
	set_kind("binary")
	add_languages("c23")
	add_files("game/*.c")
	add_files("global/*.c")
	add_includedirs("./")
	add_headerfiles("game/*.h")
	add_headerfiles("global/*.h")
	add_headerfiles("specific/*.h")
	set_warnings("all","error")
	set_warnings("extra","error")
	set_warnings("pedantic", "error")
	add_packages("miniaudio")
	add_cflags("cl::/experimental:c11atomics")
	add_ldflags("cl::/SUBSYSTEM:WINDOWS")
	add_vectorexts("all")
	on_load("windows", function(target)
		target:add("syslinks","Msacm32","d3d9","ddraw","dsound","Winmm","Gdi32","Advapi32","user32","dxgi", "dxguid","dinput8","xaudio2_9redist","Ole32")
		target:add("defines","XAUDIO2_HELPER_FUNCTIONS","WIN32_LEAN_AND_MEAN","NOMINMAX", "_CRT_SECURE_NO_WARNINGS", "COBJMACROS", "CINTERFACE")
		target:set("runtimes",is_mode("debug") and "MTd" or "MT")
		target:add("packages","xaudio2redist")
	end)
	if(is_mode("debug")) then 
		add_defines("DO_LOG")
		add_defines("_DEBUG")
	end

	on_config("windows", function(target)
		print("ON CONFIG")
		target:set("rundir","$(projectdir)/TestFiles")
		target:add("files", "$(scriptdir)/specific/windows/*.c")
		target:add("files","$(scriptdir)/tomb4/tomb4.rc")
	end)

	add_defines("_USE_MATH_DEFINES")
target_end()