#ifndef TOMB4_SPECIFIC_CLIPPING_H
#define TOMB4_SPECIFIC_CLIPPING_H

typedef struct D3DTLBUMPVERTEX D3DTLBUMPVERTEX;
typedef struct _D3DTLVERTEX _D3DTLVERTEX;

int ZClipper(int n, D3DTLBUMPVERTEX* in, D3DTLBUMPVERTEX* out);
int visible_zclip(_D3DTLVERTEX* v0, _D3DTLVERTEX* v1, _D3DTLVERTEX* v2);
int XYUVGClipper(int n, D3DTLBUMPVERTEX* in);


#endif// TOMB4_SPECIFIC_CLIPPING_H
