#ifndef TOMB4_SPECIFIC_DXINFO_H
#define TOMB4_SPECIFIC_DXINFO_H
typedef struct DXDIRECTDRAWINFO DXDIRECTDRAWINFO;
typedef struct DXDIRECTSOUNDINFO DXDIRECTSOUNDINFO;
typedef struct DXINFO {
	int nDDInfo;
	int nDSInfo;
	DXDIRECTDRAWINFO* DDInfo;
	DXDIRECTSOUNDINFO* DSInfo;
	int nDD;
	int nD3D;
	int nDisplayMode;
	int nTexture;
	int nDS;
} DXINFO;
#endif// TOMB4_SPECIFIC_DXINFO_H
