#ifndef SPECIFIC_WINDOWS_WINAPP_H
#define SPECIFIC_WINDOWS_WINAPP_H
#include "specific/windows/dxinfo.h"
#include "specific/windows/dxptr.h"
#include <windows.h>
#include <d3dtypes.h>
typedef struct WINAPP {
	HINSTANCE hInstance;
	HWND hWnd;
	WNDCLASS WindowClass;
	DXINFO DXInfo;
	DXPTR dx;
	HANDLE mutex;
	float fps;
	HACCEL hAccel;
	int SetupComplete;
	int BumpMapping;
	int TextureSize;
	int BumpMapSize;
	int mmx;
	int Filtering;
	int Volumetric;
	int SoundDisabled;
	int StartFlags;
	int fmv;
	int Desktopbpp;
	int AutoTarget;
} WINAPP;
#endif// SPECIFIC_WINDOWS_WINAPP_H
