#ifndef WINAPP_INCLUDED
#define WINAPP_INCLUDED
#include "specific/windows/dxinfo.h"
#include "specific/windows/dxptr.h"
#include <windows.h>
#include "global/types.h"
#include <d3dtypes.h>
typedef struct WINAPP {
	HINSTANCE hInstance;
	HWND hWnd;
	WNDCLASS WindowClass;
	DXINFO DXInfo;
	DXPTR dx;
	HANDLE mutex;
	float fps;
	HACCEL hAccel;
	bool SetupComplete;
	long BumpMapping;
	long TextureSize;
	long BumpMapSize;
	long mmx;
	long Filtering;
	long Volumetric;
	long SoundDisabled;
	long StartFlags;
	long fmv;
	long Desktopbpp;
	long AutoTarget;
} WINAPP;
#endif