#ifndef TOMB4_GAME_DXDIRECTSOUNDINFO_H
#define TOMB4_GAME_DXDIRECTSOUNDINFO_H
struct DXDIRECTSOUNDINFO {
	char Name[30];
	char About[80];
	LPGUID lpGuid;
	GUID Guid;
};
#endif // TOMB4_GAME_DXDIRECTSOUNDINFO_H
