#ifndef TOMB4_SPECIFIC_DXZBUFFERINFO_H
#define TOMB4_SPECIFIC_DXZBUFFERINFO_H
#include <ddraw.h>
typedef struct DXZBUFFERINFO {
	DDPIXELFORMAT ddpf;
	unsigned long bpp;
} DXZBUFFERINFO;
#endif// TOMB4_SPECIFIC_DXZBUFFERINFO_H
