#ifndef TOMB4_GAME_ANIMCOMMANDS_H
#define TOMB4_GAME_ANIMCOMMANDS_H
enum anim_commands {
	ACMD_NULL,
	ACMD_SETPOS,
	ACMD_JUMPVEL,
	ACMD_FREEHANDS,
	ACMD_KILL,
	ACMD_PLAYSFX,
	ACMD_FLIPEFFECT
};
#endif // TOMB4_GAME_ANIMCOMMANDS_H
