#ifndef TOMB4_GAME_ANIMCOMMANDS_H
#define TOMB4_GAME_ANIMCOMMANDS_H
typedef enum anim_commands {
	ACMD_NULL,
	ACMD_SETPOS,
	ACMD_JUMPVEL,
	ACMD_FREEHANDS,
	ACMD_KILL,
	ACMD_PLAYSFX,
	ACMD_FLIPEFFECT
} anim_commands;
#endif // TOMB4_GAME_ANIMCOMMANDS_H
