#ifndef TOMB4_GAME_CAMERATYPE_H
#define TOMB4_GAME_CAMERATYPE_H
enum camera_type {
	CHASE_CAMERA,
	FIXED_CAMERA,
	LOOK_CAMERA,
	COMBAT_CAMERA,
	CINEMATIC_CAMERA,
	HEAVY_CAMERA,
};
#endif // TOMB4_GAME_CAMERATYPE_H
