#ifndef TOMB4_GAME_DELTAPAK_H
#define TOMB4_GAME_DELTAPAK_H
typedef struct NODELOADHEADER NODELOADHEADER;
typedef struct PACKNODE PACKNODE;
typedef struct RTDECODE RTDECODE;
typedef struct OBJECT_INFO OBJECT_INFO;
typedef struct ITEM_INFO ITEM_INFO;
typedef struct PHD_VECTOR PHD_VECTOR;
void handle_cutseq_triggering(int name);
void do_new_cutscene_camera();
void InitPackNodes(NODELOADHEADER* lnode, PACKNODE* pnode, char* packed, int numnodes);
void DecodeAnim(PACKNODE* node, int num_nodes, int frame, int flags);
short DecodeTrack(char* packed, RTDECODE* decode);
short GetTrackWord(int off, char* packed, int packmethod);
void frigup_lara();
void updateAnimFrame(PACKNODE* node, int flags, short* frame);
void* cutseq_malloc(int size);
void finish_cutseq();
void DrawCutSeqActors();
void CalcActorLighting(ITEM_INFO* item, OBJECT_INFO* obj, short* rot);
void GetJointAbsPositionCutSeq(ITEM_INFO* item, OBJECT_INFO* obj, short* rot, PHD_VECTOR* pos);
void CalculateObjectLightingLaraCutSeq();
void third_cutseq_control();
void fourth_cutseq_init();
void fourth_cutseq_control();
void fourth_cutseq_end();
void fifth_cutseq_control();
void fifth_cutseq_end();
void sixth_cutseq_init();
void sixth_cutseq_control();
void sixth_cutseq_end();
void seventh_cutseq_init();
void seventh_control();
void eighth_control();
void ninth_cutseq_init();
void ninth_control();
void tenth_cutseq_init();
void tenth_cutseq_control();
void tenth_cutseq_end();
void eleventh_cutseq_init();
void eleventh_cutseq_control();
void twelth_cutseq_init();
void twelth_cutseq_end();
void thirteen_end();
void fourteen_end();
void fourteen_control();
void fifteen_init();
void fifteen_control();
void fifteen_end();
void sixteen_init();
void sixteen_control();
void sixteen_end();
void seventeen_control();
void seventeen_end();
void eighteen_init();
void eighteen_control();
void eighteen_end();
void nineteen_init();
void nineteen_control();
void nineteen_end();
void twenty_control();
void twenty_end();
void twentyone_init();
void twentyone_end();
void twentythree_init();
void twentythree_control();
void twentythree_end();
void twentyfour_init();
void twentyfour_control();
void twentyfour_end();
void twentyfive_control();
void twentyfive_end();
void twentyfive_init();
void twentysix_control();
void twentyseven_init();
void twentyseven_control();
void twentyseven_end();
void twentytwo_init();
void twentytwo_end();
void do_spade_meshswap();
void do_key_meshswap();
void cutseq_shoot_pistols(int left_or_right);
void trigger_weapon_dynamics(int left_or_right);
void deal_with_pistols();
void cutseq_kill_item(int num);
ITEM_INFO* cutseq_restore_item(int num);
int Load_and_Init_Cutseq(int num);
void init_cutseq_actors(char* data, int resident);
void init_voncroy_meshbits(int num);
void DelsHandyTeleportLara(int x, int y, int z, int yrot);
void nail_intelligent_object(short num);
void handle_lara_chatting(short* _ranges);
void handle_actor_chatting(int speechslot, int node, int slot, int objslot, short* _ranges);
void trigger_item_in_room(int room_number, int object_number);
void untrigger_item_in_room(int room_number, int object_number);
ITEM_INFO* find_a_fucking_item(int object_number);
void special2_end();
void special2_init();
void special3_end();
void special3_control();
void special1_init();
void special1_end();
#ifdef TIMES_LEVEL
void times_init();
void times_control();
#endif

extern int cutseq_trig;
extern int cutseq_num;
extern int GLOBAL_playing_cutseq;
extern int GLOBAL_cutseq_frame;


#endif// TOMB4_GAME_DELTAPAK_H
