#ifndef TOMB4_GAME_ITEMLIGHT_H
#define TOMB4_GAME_ITEMLIGHT_H
#include "game/pclight.h"
typedef struct ITEM_LIGHT {
	int r;
	int g;
	int b;
	int ambient;
	int rs;
	int gs;
	int bs;
	int fcnt;
	PCLIGHT CurrentLights[21];
	PCLIGHT PrevLights[21];
	int nCurrentLights;
	int nPrevLights;
	int room_number;
	PHD_VECTOR item_pos;
	void* pCurrentLights;
	void* pPrevLights;
} ITEM_LIGHT;
#endif// TOMB4_GAME_ITEMLIGHT_H
