#ifndef TOMB4_GAME_LARAGUNSTATUS_H
#define TOMB4_GAME_LARAGUNSTATUS_H
enum lara_gun_status {
	LG_NO_ARMS,
	LG_HANDS_BUSY,
	LG_DRAW_GUNS,
	LG_UNDRAW_GUNS,
	LG_READY,
	LG_FLARE,
};
#endif // TOMB4_GAME_LARAGUNSTATUS_H
