#ifndef TOMB4_GAME_MONOSCREENSTRUCT_H
#define TOMB4_GAME_MONOSCREENSTRUCT_H
#include "specific/haltexture.h"
typedef struct MONOSCREEN_STRUCT {
	HAL_TEXTURE hal;
} MONOSCREEN_STRUCT;
#endif // TOMB4_GAME_MONOSCREENSTRUCT_H
