#ifndef TOMB4_GAME_MONOSCREENSTRUCT_H
#define TOMB4_GAME_MONOSCREENSTRUCT_H
struct MONOSCREEN_STRUCT {
	IDirect3DTexture2* tex;
	IDirectDrawSurface4* surface;
};
#endif // TOMB4_GAME_MONOSCREENSTRUCT_H
