#ifndef TOMB4_GAME_SFXTYPES_H
#define TOMB4_GAME_SFXTYPES_H
typedef enum sfx_types {
	SFX_LANDANDWATER = 0,
	SFX_LANDONLY = 0x4000,
	SFX_WATERONLY = 0x8000
} sfx_types;
#endif // TOMB4_GAME_SFXTYPES_H
