#ifndef TOMB4_GAME_TRIGGERTYPES_H
#define TOMB4_GAME_TRIGGERTYPES_H
typedef enum trigger_types {
	TRIGGER,
	PAD,
	SWITCH,
	KEY,
	PICKUP,
	HEAVY,
	ANTIPAD,
	COMBAT,
	DUMMY,
	ANTITRIGGER,
	HEAVYSWITCH,
	HEAVYANTITRIGGER,
	MONKEY
} trigger_types;
#endif // TOMB4_GAME_TRIGGERTYPES_H
