#ifndef TOMB4_GAME_WEAPONTYPES_H
#define TOMB4_GAME_WEAPONTYPES_H
typedef enum weapon_types {
	WEAPON_NONE,
	WEAPON_PISTOLS,
	WEAPON_REVOLVER,
	WEAPON_UZI,
	WEAPON_SHOTGUN,
	WEAPON_GRENADE,
	WEAPON_CROSSBOW,
	WEAPON_FLARE,
	WEAPON_TORCH
} weapon_types;
#endif// TOMB4_GAME_WEAPONTYPES_H
