#ifndef WEAPON_TYPES_INCLUDED
#define WEAPON_TYPES_INCLUDED
enum weapon_types {
	WEAPON_NONE,
	WEAPON_PISTOLS,
	WEAPON_REVOLVER,
	WEAPON_UZI,
	WEAPON_SHOTGUN,
	WEAPON_GRENADE,
	WEAPON_CROSSBOW,
	WEAPON_FLARE,
	WEAPON_TORCH
};
#endif